# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1qgx8gafa70l91x3z57lshvsfgq4v2flqa50iazjhg8m2asdkwlr";
    aarch64-linux = "18fhldsn90xdm5ajk533b6hwwz9fl1m884bb5zk5v3fvjlw4bbdf";
    x86_64-darwin = "04j58ivj82iwb4zmnwfsjx8ji94w1srcmd3sspi3sg126d08n02n";
    aarch64-darwin = "0rvivr7al1vzbwhjw58v61r8y301pnvg1c3jrqrmnpxdqps73kss";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.1.0/gh-contribs_0.1.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.1.0/gh-contribs_0.1.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.1.0/gh-contribs_0.1.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.1.0/gh-contribs_0.1.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "gh-contribs";
  version = "0.1.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./gh-contribs $out/bin/gh-contribs
  '';

  meta = {
    description = "Your GitHub contribution rhythm, in the terminal";
    homepage = "https://github.com/Josef-Hlink/gh-contribs";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
