# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1c8xn4l9m50vd152daj17092iz1p1gx3ilfprvvvbqvffl5lsbd8";
    aarch64-linux = "0x3v8qsrfglskc77y2nqffpwrj0nm9gp9xa29xgqqsplmiwcp2pi";
    x86_64-darwin = "1b5yg9zdvn4c0zxd4vh6p2mjsmvrxjcav34xnrj5883y0d61yfyi";
    aarch64-darwin = "161vq91cc9d1czn7z55jy260i5f1qdkr23vshjzaqij6xh5hw3hz";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.0.1/gh-contribs_0.0.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.0.1/gh-contribs_0.0.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.0.1/gh-contribs_0.0.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/Josef-Hlink/gh-contribs/releases/download/v0.0.1/gh-contribs_0.0.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "gh-contribs";
  version = "0.0.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./gh-contribs $out/bin/gh-contribs
  '';

  meta = {
    description = "Your GitHub contribution rhythm, in the terminal";
    homepage = "https://github.com/Josef-Hlink/gh-contribs";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
