# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  fzf,
  makeWrapper,
  tmux,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "18d9ga14yv0a3ld7h4svpiwyix5a2z9j5a3a7dzqh329027pk5g4";
    aarch64-linux = "131p047c3sdy1fmh0z5bhgbg145vsbq16kpflcpdfmv0vcdi8h11";
    x86_64-darwin = "13hny0gvkqrsgv8pdka5nhvxks6vws9vzs1zsrmnss5kqz0a2nbg";
    aarch64-darwin = "1lvhlybx0ldrl7z6as8f3zxii0j5g2v54nq7h9vvyq541j218691";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.0/twin_0.2.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.0/twin_0.2.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.0/twin_0.2.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.0/twin_0.2.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "twin";
  version = "0.2.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./twin $out/bin/twin
    wrapProgram $out/bin/twin --prefix PATH : ${lib.makeBinPath ([ tmux fzf ])}
  '';

  meta = {
    description = "tmux workspace manager driven by TOML recipes";
    homepage = "https://github.com/Josef-Hlink/twin";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
