# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  fzf,
  makeWrapper,
  tmux,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1497a6z68fi7svqf973kvifqb53k4ac52bay8zza6rclirzr09vh";
    aarch64-linux = "1z9446insrpjyfqyzgmslxi0wq2ynaln5wfpf26a9jhxmmcbhhiw";
    x86_64-darwin = "1yzhv6k1baa2izgmpnmfaykfjb10ygq63cfsw072l7lk8p2nacqb";
    aarch64-darwin = "1nx4qnbdli3a6ihpld76ym7sh2naz77cav2b9snsz1f8hlmvbhxb";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.3/twin_0.2.3_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.3/twin_0.2.3_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.3/twin_0.2.3_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.3/twin_0.2.3_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "twin";
  version = "0.2.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./twin $out/bin/twin
    wrapProgram $out/bin/twin --prefix PATH : ${lib.makeBinPath ([ tmux fzf ])}
  '';

  meta = {
    description = "tmux workspace manager driven by TOML recipes";
    homepage = "https://github.com/Josef-Hlink/twin";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
