# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  fzf,
  makeWrapper,
  tmux,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "05qs2y9d41yinvjznz5lvhsczh08jya6xq5yyl86l7v92pwhdqi8";
    aarch64-linux = "0w7ajlmw5vp0ww2qghips08lm2fmmb8n82mz309hc3izl77nr5ax";
    x86_64-darwin = "11fnq33mxrs369dhkzyi3vq08xx20n39dg9shllcmsm5kq7ny145";
    aarch64-darwin = "0ia918irdw97kzdagawmaplwwsm4yxsddkb071jl5xxf62dp08ly";
  };

  urlMap = {
    x86_64-linux = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.2/twin_0.2.2_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.2/twin_0.2.2_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.2/twin_0.2.2_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/Josef-Hlink/twin/releases/download/v0.2.2/twin_0.2.2_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "twin";
  version = "0.2.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./twin $out/bin/twin
    wrapProgram $out/bin/twin --prefix PATH : ${lib.makeBinPath ([ tmux fzf ])}
  '';

  meta = {
    description = "tmux workspace manager driven by TOML recipes";
    homepage = "https://github.com/Josef-Hlink/twin";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
